"""Generator + freshness check for the frozen stdlib stub table — one self-contained command.

Introspects the allowlisted stdlib types (``stubs.ALLOWLIST``) under each supported Python
version (``stubs.SUPPORTED_VERSIONS`` — the single source of truth), keeps the callable,
non-underscore members, and writes the INTERSECTION across versions to
``src/claude_ast/ingest/python/_stub_table.py`` — a frozen, hermetic literal. It orchestrates
the multi-interpreter matrix itself (re-invoking under ``uv run --python``), so there is no
shell/Make glue. All interpreter-dependence lives here; the shipped table and the index-time
lookup stay pure.

This is the Python backend's tooling: it lives under ``tools/python/`` mirroring
``src/claude_ast/ingest/python/``, so a future JS/TS backend's equivalent has a parallel home
under ``tools/typescript/``. Usage (from the repo root)::

    uv run python tools/python/gen_stubs.py          # regenerate the committed table
    uv run python tools/python/gen_stubs.py check    # CI gate: exit non-zero if the table is stale
"""

from __future__ import annotations

import importlib
import json
import subprocess
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[2]  # tools/python/gen_stubs.py -> repo root
sys.path.insert(0, str(_ROOT / "src"))

from claude_ast.ingest.python.stubs import (  # noqa: E402  (after sys.path setup)
    ALLOWLIST,
    SUPPORTED_VERSIONS,
    spec_fingerprint,
)

_SELF = Path(__file__).resolve()
_OUT = _ROOT / "src" / "claude_ast" / "ingest" / "python" / "_stub_table.py"


def _members(module: str, type_name: str) -> list[str]:
    """Callable, non-underscore members of a stdlib type on the running interpreter."""
    try:
        tp = getattr(importlib.import_module(module), type_name)
    except (ImportError, AttributeError):
        return []
    out: set[str] = set()
    for name in dir(tp):  # dir() walks the MRO -> inherited members included
        if name.startswith("_"):
            continue  # drop dunders AND single-underscore privates (unstable internals)
        try:
            attr = getattr(tp, name)
        except Exception:  # noqa: BLE001  (a descriptor that errors on class access — skip)
            continue
        if callable(attr):  # properties / data attrs (Path.name, datetime.max) are not
            out.add(name)
    return sorted(out)


def _dump() -> None:
    """Print this interpreter's members as JSON. Invoked as a subprocess, once per version."""
    version = f"{sys.version_info.major}.{sys.version_info.minor}"
    table = {f"{module}.{tp}": _members(module, tp) for module, tp in ALLOWLIST}
    json.dump({"version": version, "table": table}, sys.stdout)


def _dump_under(version: str) -> dict:
    """Run this script's ``dump`` under ``version`` via uv and return the parsed result."""
    proc = subprocess.run(
        ["uv", "run", "--python", version, "--no-project", "python", str(_SELF), "dump"],
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        raise SystemExit(f"introspection under Python {version} failed:\n{proc.stderr}")
    return json.loads(proc.stdout)


def _render() -> str:
    """Introspect every supported version, intersect the members, render the table module."""
    dumps = [_dump_under(v) for v in SUPPORTED_VERSIONS]
    # A member survives only if present on every supported version -> version-skew-safe in range.
    quals = set.intersection(*(set(d["table"]) for d in dumps))
    table: dict[str, list[str]] = {}
    for qual in sorted(quals):
        members = set.intersection(*(set(d["table"].get(qual, [])) for d in dumps))
        if members:
            table[qual] = sorted(members)

    lines = [
        "# GENERATED by tools/python/gen_stubs.py — DO NOT EDIT. Regenerate with the same command.",
        "# type qualname -> callable members present on EVERY supported Python version",
        f"# {list(SUPPORTED_VERSIONS)}; consulted at index time as a pure, hermetic lookup.",
        "",
        "TABLE: dict[str, frozenset[str]] = {",
    ]
    for qual, members in table.items():
        inner = ", ".join(repr(m) for m in members)
        lines.append(f"    {qual!r}: frozenset({{{inner}}}),")
    lines += ["}", "", f"FINGERPRINT = {spec_fingerprint()!r}", ""]
    return "\n".join(lines)


def _generate() -> None:
    _OUT.write_text(_render())
    print(f"wrote {_OUT.relative_to(_ROOT)}", file=sys.stderr)


def _check() -> None:
    """CI gate: regenerate in memory and fail if it differs from what's committed."""
    current = _OUT.read_text() if _OUT.exists() else ""
    if _render() != current:
        raise SystemExit(
            "stub table is stale — run `uv run python tools/python/gen_stubs.py` and commit"
        )
    print("stub table is up to date", file=sys.stderr)


if __name__ == "__main__":
    command = sys.argv[1] if len(sys.argv) > 1 else "generate"
    if command == "dump":  # internal: the per-interpreter subprocess entry point
        _dump()
    elif command == "generate":
        _generate()
    elif command == "check":
        _check()
    else:
        raise SystemExit(__doc__)
