"""Python backend — stub resolution on external types via the frozen typeshed tables.

`p: Path; p.exists()` resolves to a possible-tier STUB edge on an EXTERNAL member node, using the
hermetic typeshed member table (`_typeshed_table.py`, generated by tools/python/gen_typeshed.py).
The table's own freshness is guarded by `tools/python/gen_typeshed.py check` and
`test_typeshed_table.py`; these tests exercise the *resolution* that consults it.
"""

from claude_ast.index import Index


def _external_deps(index: Index, sym: str) -> set[tuple[str, str]]:
    return {(d.id, d.tier) for d in index.find_dependencies(sym) if d.external}


def test_stub_resolves_a_member_on_an_annotated_external_type(tmp_path):
    (tmp_path / "m.py").write_text(
        "from pathlib import Path\n\n\ndef f(p: Path):\n    return p.exists()\n"
    )
    index = Index.build(tmp_path)

    deps = {(d.id, d.kind, d.tier, d.external) for d in index.find_dependencies("m.f")}
    assert ("pathlib.Path.exists", "call", "possible", True) in deps
    edge = next(e for e in index.graph.out_edges("m.f") if e.dst == "pathlib.Path.exists")
    assert edge.resolution.source.value == "stub"


def test_stub_resolves_a_builtin_type_member(tmp_path):
    (tmp_path / "m.py").write_text("def f(d: dict):\n    return d.get('x')\n")
    index = Index.build(tmp_path)
    assert ("builtins.dict.get", "possible") in _external_deps(index, "m.f")


def test_stub_resolves_a_constructed_external_receiver(tmp_path):
    # `p = Path(); p.exists()` — construction inference of an external type also feeds stubs.
    (tmp_path / "m.py").write_text(
        "from pathlib import Path\n\n\ndef f():\n    p = Path()\n    return p.exists()\n"
    )
    index = Index.build(tmp_path)
    assert ("pathlib.Path.exists", "possible") in _external_deps(index, "m.f")


def test_stub_resolves_a_dotted_external_type(tmp_path):
    (tmp_path / "m.py").write_text(
        "import datetime\n\n\ndef f(d: datetime.date):\n    return d.isoformat()\n"
    )
    index = Index.build(tmp_path)
    assert ("datetime.date.isoformat", "possible") in _external_deps(index, "m.f")


def test_stub_resolves_a_type_beyond_the_old_allowlist(tmp_path):
    # The typeshed table covers the full stdlib, not a 24-type allowlist: `q: Queue; q.put()`
    # now resolves where the old hand-listed table declined.
    (tmp_path / "m.py").write_text(
        "from queue import Queue\n\n\ndef f(q: Queue):\n    return q.put(1)\n"
    )
    index = Index.build(tmp_path)
    assert ("queue.Queue.put", "possible") in _external_deps(index, "m.f")


def test_unknown_member_declines(tmp_path):
    (tmp_path / "m.py").write_text(
        "from pathlib import Path\n\n\ndef f(p: Path):\n    return p.zzznope()\n"
    )
    index = Index.build(tmp_path)
    assert _external_deps(index, "m.f") == set()


def test_an_in_tree_type_shadows_a_stdlib_stub(tmp_path):
    # A local class named `Path` is in-tree -> resolves there, never to the stdlib stub.
    (tmp_path / "m.py").write_text(
        "class Path:\n    def exists(self):\n        ...\n\n\n"
        "def f(p: Path):\n    return p.exists()\n"
    )
    index = Index.build(tmp_path)
    deps = {(d.id, d.external) for d in index.find_dependencies("m.f")}
    assert ("m.Path.exists", False) in deps
    assert not any(external for _, external in deps)  # no external stub edge
