"""Python backend — stub resolution on external types + the frozen-table freshness checks.

`p: Path; p.exists()` resolves to a possible-tier STUB edge on an EXTERNAL member node,
via the hermetic stdlib table (generated by tools/python/gen_stubs.py). The last two tests are the
regeneration detector: they fail when the committed table drifts from its spec, or from the
running interpreter's stdlib — i.e. exactly when someone should regenerate the table.
"""

import importlib

from claude_ast.index import Index
from claude_ast.ingest.python import stubs


def _external_deps(index: Index, sym: str) -> set[tuple[str, str]]:
    return {(d.id, d.tier) for d in index.find_dependencies(sym) if d.external}


def test_stub_resolves_a_member_on_an_annotated_external_type(tmp_path):
    (tmp_path / "m.py").write_text(
        "from pathlib import Path\n\n\ndef f(p: Path):\n    return p.exists()\n"
    )
    index = Index.build(tmp_path)

    deps = {(d.id, d.kind, d.tier, d.external) for d in index.find_dependencies("m.f")}
    assert ("pathlib.Path.exists", "call", "possible", True) in deps
    edge = next(e for e in index.graph.out_edges("m.f") if e.dst == "pathlib.Path.exists")
    assert edge.resolution.source.value == "stub"


def test_stub_resolves_a_builtin_type_member(tmp_path):
    (tmp_path / "m.py").write_text("def f(d: dict):\n    return d.get('x')\n")
    index = Index.build(tmp_path)
    assert ("builtins.dict.get", "possible") in _external_deps(index, "m.f")


def test_stub_resolves_a_constructed_external_receiver(tmp_path):
    # `p = Path(); p.exists()` — construction inference of an external type also feeds stubs.
    (tmp_path / "m.py").write_text(
        "from pathlib import Path\n\n\ndef f():\n    p = Path()\n    return p.exists()\n"
    )
    index = Index.build(tmp_path)
    assert ("pathlib.Path.exists", "possible") in _external_deps(index, "m.f")


def test_stub_resolves_a_dotted_external_type(tmp_path):
    (tmp_path / "m.py").write_text(
        "import datetime\n\n\ndef f(d: datetime.date):\n    return d.isoformat()\n"
    )
    index = Index.build(tmp_path)
    assert ("datetime.date.isoformat", "possible") in _external_deps(index, "m.f")


def test_unknown_member_declines(tmp_path):
    (tmp_path / "m.py").write_text(
        "from pathlib import Path\n\n\ndef f(p: Path):\n    return p.zzznope()\n"
    )
    index = Index.build(tmp_path)
    assert _external_deps(index, "m.f") == set()


def test_non_callable_member_declines(tmp_path):
    # `Path.name` is a property, not a callable method -> not in the table -> p.name() declines.
    (tmp_path / "m.py").write_text(
        "from pathlib import Path\n\n\ndef f(p: Path):\n    return p.name()\n"
    )
    index = Index.build(tmp_path)
    assert _external_deps(index, "m.f") == set()


def test_type_outside_the_allowlist_declines(tmp_path):
    (tmp_path / "m.py").write_text(
        "from os import PathLike\n\n\ndef f(p: PathLike):\n    return p.foo()\n"
    )
    index = Index.build(tmp_path)
    assert _external_deps(index, "m.f") == set()


def test_an_in_tree_type_shadows_a_stdlib_stub(tmp_path):
    # A local class named `Path` is in-tree -> resolves there, never to the stdlib stub.
    (tmp_path / "m.py").write_text(
        "class Path:\n    def exists(self):\n        ...\n\n\n"
        "def f(p: Path):\n    return p.exists()\n"
    )
    index = Index.build(tmp_path)
    deps = {(d.id, d.external) for d in index.find_dependencies("m.f")}
    assert ("m.Path.exists", False) in deps
    assert not any(external for _, external in deps)  # no external stub edge


# --- regeneration detection: these fail when the committed table should be rebuilt ---


def test_stub_table_matches_its_spec_fingerprint():
    # Catches an allowlist / supported-versions / generator-logic edit that skipped regeneration.
    assert stubs.spec_fingerprint() == stubs.TABLE_FINGERPRINT, (
        "stub table is stale versus its spec — run `uv run python tools/python/gen_stubs.py`"
    )


def test_every_stubbed_member_exists_on_this_interpreter():
    # A committed member absent on the running (in-supported-range) Python would mint a false
    # edge; this catches that class of staleness without needing the full version matrix.
    for qual, members in stubs.TABLE.items():
        module, _, type_name = qual.rpartition(".")
        tp = getattr(importlib.import_module(module), type_name)
        for member in members:
            assert callable(getattr(tp, member, None)), (
                f"{qual}.{member} missing/non-callable on this Python — regenerate the stub table"
            )
